### ISSUE TITLE
Kun bygg hvis endringer i gitt docker-fil

### ISSUE THREAD

**Issue by arnfinn** [Rapporteket/docker#45]
Ved ny release, f.eks., vil det være mest hensiktsmessig at kun Docker-image som er endret får en ny release-tag. Mulig [dorny/path-filter](https://www.github.com/dorny/paths-filter) kunne vært brukt.

Noe ala dette:

```yml
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          package1: src/package1
          package2: src/package2

  # JOB to build and test each of modified packages
  build:
    needs: changes
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['package1', 'package2'] if both package folders contains changes
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - ...
```
